### ISSUE TITLE
Module is distributed as ES6 and can't be bundled

### ISSUE THREAD

**Issue by chocolateboy** [bendrucker/angular-annotation-decorator#2]
Thanks for this. It's much simpler than the other implementations I've looked at and has fewer restrictions. However, I can't actually use it as-is as it's shipped as an ES6 module. By default, bundlers such as Browserify (with Babelify), don't transpile files under `node_modules`. I could make an exception for this particular module, but I'd rather fix the issue at source than hardwire a one-off workaround.

Modules that target Node.js can afford to require certain ES6 features, but that's not the case in the browser, so modules written in ES6 (and CoffeeScript/TypeScript &c.) are usually transpiled to ES5 for distribution.

**Comment by bendrucker** [comment]
I'll happily take a PR converting to ES5. Wrote this forever ago. No arguments on transpilation, I'm well aware of the gotchas and generally think ES6 is a waste of time and energy.
